services:
  zabbix-mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      MYSQL_ROOT_PASSWORD: rootpass
    command:
      [
        "--collation-server=utf8mb4_bin",
        "--max_allowed_packet=256M",
        "--innodb_log_file_size=128M",
        "--wait_timeout=28800",
        "--log_bin_trust_function_creators=1",
      ]
    volumes:
      - zabbix_mysql_data:/var/lib/mysql
    networks:
      - messaging-net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-latest
    depends_on:
      - zabbix-mysql
    environment:
      DB_SERVER_HOST: zabbix-mysql
      DB_SERVER_PORT: 3306
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
    ports:
      - "10051:10051"
    networks:
      - messaging-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-latest
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      PHP_TZ: Europe/Lisbon
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "8080:8080"
    networks:
      - messaging-net

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-latest
    depends_on:
      - zabbix-server
    volumes:
      - ./scripts:/usr/lib/zabbix/externalscripts
    environment:
      ZBX_SERVER_HOST: zabbix-server
    networks:
      - messaging-net

  zabbix-agent-kafka:
    image: zabbix/zabbix-agent:alpine-latest
    container_name: zabbix-agent-kafka
    environment:
      ZBX_SERVER_HOST: zabbix-server
      HOSTNAME: Kafka-Container
    volumes:
      - ./scripts:/etc/zabbix/scripts:ro
    depends_on:
      - kafka
    networks:
      - messaging-net

  kafka:
    image: bitnami/kafka:3.4.0
    ports:
      - "9092:9092"
      - "9999:9999" # Expose JMX
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_JMX_PORT: 9999
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - messaging-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - messaging-net

  web-static:
    image: nginx:alpine
    volumes:
      - ./web-static:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - messaging-net

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8082:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
    networks:
      - messaging-net

  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    ports:
      - "8083:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: kafka:9092
    networks:
      - messaging-net

volumes:
  zabbix_mysql_data:
  grafana_data:
  kafka_data:

networks:
  messaging-net:
    name: messaging-net
